name: Action Server
on: 
  push:
    branches:
    - 'main'
    paths:
    - 'actions/**'

jobs:
  my_first_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2
      - name: Action Server
        uses: RasaHQ/action-server-gha@main
        with:
          # Path to the directory with actions.
          actions_directory: ./actions
          # Path to the requirements.txt file.
          requirements_file: ./actions/requirements-actions.txt
          # Name of the docker registry which the Docker image should be published to.
          docker_registry: docker.io
          # Login name for the Docker registry.
          docker_registry_login: ${{ secrets.DOCKER_HUB_LOGIN }}
          # Password for the Docker registry.
          docker_registry_password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          # Docker image name.
          docker_image_name: 'jpark2111/wealthbuild_rasa_action_server'
          # Docker image tag.
          docker_image_tag: 1.17.2022
          # Push a docker image to the registry. If `False` the user can add manual extra steps in their workflow which use the built image.
          docker_registry_push: true
          # Path to a custom Dockerfile.
          dockerfile: Dockerfile
          # Version of the Rasa SDK which should be used to build the image.
          rasa_sdk_version: latest